### ISSUE TITLE
Accessibility through specifying metainfo

### ISSUE THREAD

**Issue by normanbrobinson** [jonsneyers/FLIF#15]
Would it be possible to include filename, and text description (http://www.w3.org/WAI/WCAG20/quickref/#text-equiv) in metainfo (http://owl.phy.queensu.ca/~phil/exiftool/) such that the file format could be used to ensure accessibility for people with disabilities (as well as web crawlers or search engines) and is tied to the file itself? By doing so, we could specify web tools pull that information to generate alt text in HTML, as well as assistive technologies (screen readers) could pull it from the image itself.

**Comment by jonsneyers** [comment]
Let's discuss this and other metadata stuff here: https://github.com/jonsneyers/FLIF/issues/17
