### ISSUE TITLE
Portability and cross-compilation

### ISSUE THREAD

**Issue by r-lyeh** [jonsneyers/FLIF#18]
Hello there,

I made the following changes in the source code. Would you be interested in pull requests for any of them?

- win32 port
- msvc friendly
- removed libpng, zlib and getopt dependencies
- added stb image and miniz so it loads more lossless image formats now
- fixed a crash when no args were provided
- fixed mixed up c/c++ linkage problems

**Comment by jonsneyers** [comment]
Certainly! As long as you accept the CLA. If you removed libpng/zlib/getopt dependencies, does that mean it can no longer read/write png files?

**Comment by hrj** [comment]
I was also going to suggest some re-structuring. I have transpiled the code to JS via emscripten. I was going to wait till the demo is up before making the suggestions, but anyway, here goes:

* Split `flif.cpp` into separate files, such as: `encoder.cpp`, `decoder.cpp` and `flip.cpp`
* Split remaining dependencies such that encoding, decoding need not depend on libpng. That is, have a separate source file to deal with import / export.

**Comment by r-lyeh** [comment]
- Accepting CLA no problem.
- New libraries licensed as following: getopt is under bsd4, getopt-long is under bsd3, stb_image and miniz are both public domain. They are all embedded in the trunk repository.
- It can still load/save png, and from now, a bunch of other additional formats as well : bmp, tga, etc .
- More info about new loading capabilities [here](https://raw.githubusercontent.com/nothings/stb/master/stb_image.h)
- More info about new saving capabilities [here](https://github.com/nothings/stb/blob/master/stb_image_write.h)

I am not an expert on licenses but my suggestion would be to release the `flif.cpp` sample program itself as GPL3 as it is, and then splitting a new de/encoding library into a less restrictive license, like ZLIB/LibPNG (or Apache2 if you are really worried about patents).

**Comment by jonsneyers** [comment]
Writing out somewhat larger PNGs is not a big problem. Not being able to load/save 16-bpc PNGs is a more important problem though. Perhaps make the libpng dependency a compile option?

Apache2 sounds like a good idea for the encoding/decoding library. And maybe something even less restrictive for a simplified decode-only library. First let's finalize the format though.

**Comment by r-lyeh** [comment]
If writing larger pngs is not a problem then I can remove miniz library as well. The Stb library is pretty awesome as it is right now. On the other hand, a very talented guy is working on the 16 bpc png support and I am sure it is only matter of time until the feature is finished and merged into master branch.

Meanwhile a directive to add extra libpng support sounds ok to me.

Would you like the PR to have a commit per feature or a single commit for everything?

**Comment by Bulat-Ziganshin** [comment]
r-lyeh, can you please share you repository or just the compiled executables? we, windows users, are interested in benchmarking the library, so the license is nothing and ready-to-run executable is everything

**Comment by jonsneyers** [comment]
One commit per feature or a single commit for everything, I don't care. But try to avoid removing features in the default compile -- so maybe keep libpng by default for now (until Stb support 16bpc) and have an option to avoid the dependency.

**Comment by r-lyeh** [comment]
@Bulat-Ziganshin, @jonsneyers :+1: to both

**Comment by r-lyeh** [comment]
@jonsneyers feel free to tweak the new PR I just sent

**Comment by jonsneyers** [comment]
Doesn't compile in GNU/Linux anymore. Can you please fix ASAP?

**Comment by r-lyeh** [comment]
can you provide a log?

**Comment by r-lyeh** [comment]
see a400f3e

**Comment by r-lyeh** [comment]
If the new makefile is still failing because of getopt compilation errors, then you may switch to new getopt for MSVC and old getopt solution for everything else, as in this commit

https://github.com/r-lyeh/FLIF/commit/623f94155e004b2e3fac0bd19f937bf9cd1ec835

**Comment by jonsneyers** [comment]
OK, fixed. I guess we better add some automated testing to avoid breaking things on some or all platforms.

**Comment by r-lyeh** [comment]
:+1:
