### ISSUE TITLE
not better compression with every kind of file :)

### ISSUE THREAD

**Issue by Safari77** [jonsneyers/FLIF#20]
https://i.imgur.com/VcyuTdJ.png
```
flif 13109 bytes
png   1941 bytes
webp   892 bytes
```

**Comment by jonsneyers** [comment]
Interesting example!
I wonder why PNG/WebP perform so well on this -- is this something that gzips very well for some reason or something?

**Comment by sipa** [comment]
How large is the maniac tree?

**Comment by jonsneyers** [comment]
Less than 10% of the total, so that's not it. This is just an image that compresses exceptionally well in PNG/WebP for some reason. For example, the corresponding lossy JPEG file at quality 70% is something like 100 times larger.
```
flif -vvvvv VcyuTdJ.png V.flif
  _____  __  (__) _____
 (___  ||  | |  ||  ___)   FLIF 0.1 [2 October 2015]
  (__  ||  |_|__||  __)    Free Lossless Image Format
    (__||______) |__)      (c) 2010-2015 J.Sneyers & P.Wuille, GNU GPL v3+

Loading input file: VcyuTdJ.png  
Input: 512x512, channels: 1, depth: 8 bit
Transforms: none
Learning a MANIAC tree. Iterating 3 times.
Header: 10 bytes. Rough data: 1669 bytes. MANIAC tree: 1042 bytes.
74% done [0/5] ENC[0,128x64]      wrote 2787 bytes    
74% done [1/5] ENC[0,128x128]      wrote 3473 bytes    
75% done [2/5] ENC[0,256x128]      wrote 5294 bytes    
76% done [3/5] ENC[0,256x256]      wrote 7155 bytes    
80% done [4/5] ENC[0,512x256]      wrote 9394 bytes    
86% done [5/5] ENC[0,512x512]      wrote 12987 bytes    
Encoding done, 12987 bytes for 512x512 pixels (0.0495bpp)
'''

**Comment by Safari77** [comment]
I found it from here
http://dsp.stackexchange.com/questions/2010/what-is-the-least-jpg-compressible-pattern-camera-shooting-piece-of-cloth-sca

**Comment by Bulat-Ziganshin** [comment]
i think that this image has a lot of LZ strings. one can test it by adding printf's to zlib decoder

**Comment by jonsneyers** [comment]
Well, every method will have pathological border cases like that (exceptionally good or bad), but it's not a real 'issue' I guess.
