### ISSUE TITLE
transparency bug?

### ISSUE THREAD

**Issue by hrj** [jonsneyers/FLIF#36]
While playing with the web demo, I saw a glitch. See the shadow below the penguin:

![fliffbug](https://cloud.githubusercontent.com/assets/345879/10269439/91ae06ae-6af5-11e5-8585-d95d32cdcb4c.png)

I hope it is self-explanatory; let me know if you need more details.

**Comment by jonsneyers** [comment]
I can't seem to reproduce this. Compressing and decompressing gives me a file that is identical to the original.

**Comment by hrj** [comment]
Sorry; my bad. It was a bug in my code, and it was not related to transparency. It was a confusion between width and height. Double goof-up!

**Comment by jonsneyers** [comment]
No worries, those things happen. Keep up the good work, I love that demo!
