### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jonsneyers/FLIF#41]
I would like to point out that identifiers like "[`__COMMMON_H__`](https://github.com/jonsneyers/FLIF/blob/78ca0adc6ff98a72497e4173383caf25afe5402f/common.h#L1)" and "[`_FLIF_H_`](https://github.com/jonsneyers/FLIF/blob/eeabed0388e8be01953eafee46447c91ef71b30c/flif.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by lucaswerkmeister** [comment]
I would like to point out that even glibc uses these conventional identifiers (example: [`stdio.h`](https://sourceware.org/git/?p=glibc.git;a=blob;f=libio/stdio.h;h=19ab0ae0b994f446d4eaac57839d0ad2b804c678;hb=HEAD#l26)).

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/jonsneyers/FLIF/commit/7c00fea586cec12992f5c9a0943f3895408b5962#diff-32f5bec80fb31433871b09021cec741dL1 "Deletion of a few underscores").
