### ISSUE TITLE
non-aggregate type

### ISSUE THREAD

**Issue by floyd-fuh** [jonsneyers/FLIF#52]
Hi there

Apart from a couple of warnings (missing return values):

`transform/../image/image.h:118:2: warning: control reaches end of non-void function [-Wreturn-type]`

I also get an error when trying to compile:

```
common.cpp:5:32: error: non-aggregate type 'const std::vector<std::string>' cannot be initialized with an initializer list
const std::vector<std::string> transforms = {"YIQ","BND","ACB","PLT","PLA","FRS","DUP","FRA","???"};
```

The error message sounds really strange to me. Any idea? My compiler (on Ubuntu 12.04.5 LTS):

```
$ clang -v
Ubuntu clang version 3.0-6ubuntu3 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

cheers,
floyd

**Comment by jonsneyers** [comment]
Looks like you need clang 3.1 :
http://clang.llvm.org/cxx_status.html
