### ISSUE TITLE
Support spatial metadata

### ISSUE THREAD

**Issue by schwehr** [jonsneyers/FLIF#7]
Please make sure to allow for spatial metadata including projection (epsg or wkt), bounding region, ground control points etc.  Needing to have side cars for the geotransform and or projection info is really painful

Background info:

- http://www.gdal.org/formats_list.html
- https://en.wikipedia.org/wiki/GeoTIFF

**Comment by jonsneyers** [comment]
Let's discuss this and other metadata stuff here: https://github.com/jonsneyers/FLIF/issues/17
